---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: cluster
spec:
  baseDomain: lab.diktio.net
  clusterName: ocptest
  clusterInstallRef:
    name: aci-ocptest
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          telco-core: core-ocptest
