- name: Create vm creation_scripts
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create temporary directory for rendered templates
      tempfile:
        state: directory
      register: temp_dir

    - name: Render Cluster Template
      template:
        src: templates/cluster.yml.j2
        dest: "{{ temp_dir.path }}/cluster.yml"

    - name: Render Node Templates
      template:
        src: templates/node.yml.j2
        dest: "{{ temp_dir.path }}/{{ hostvars[node].name }}-node.yml"
      loop: "{{ groups['nodes'] }}"
      loop_control:
        loop_var: node


